name: Untrusted CI

on:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Setup NDK_PATH
        run: echo "NDK_PATH=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV

      - name: Build
        run: |
          make all -j$(nproc)

      - name: Upload release
        uses: actions/upload-artifact@v7
        with:
          path: "build/out/BreZygisk-v*-release.zip"
          archive: false

      - name: Upload debug
        uses: actions/upload-artifact@v7
        with:
          path: "build/out/BreZygisk-v*-debug.zip"
          archive: false
