name: Trusted CI

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Setup keys
        env:
          private_key: ${{ secrets.ORG_PRIVATE_KEY }}
          public_key: ${{ secrets.ORG_PUBLIC_KEY }}
        run: |
          if [ -z "$private_key" ] || [ -z "$public_key" ]; then
            echo "Private or public key is not set."
          else
            echo "$private_key" | base64 -d > module/private_key
            echo "$public_key" | base64 -d > module/public_key
          fi

      - name: Setup NDK_PATH
        run: echo "NDK_PATH=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV

      - name: Build
        run: |
          make all -j$(nproc)

      - name: Upload release
        uses: actions/upload-artifact@v7
        with:
          path: "build/out/ReZygisk-v*-release.zip"
          archive: false

      - name: Upload debug
        uses: actions/upload-artifact@v7
        with:
          path: "build/out/ReZygisk-v*-debug.zip"
          archive: false
